name: Build Documentation
on:
  push:
    branches:
      - master
      
jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Build Documentation
        run: |
          sudo apt-get install python3 python3-pip
          sudo pip3 install sphinx sphinx_rtd_theme
          cd docs/docgen/
          python3 docgen.py ../../

      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          BRANCH: documentation
          FOLDER: docs/docgen/build/
          