name: Compile Test
on:
  push:
    branches:
      - master

env:
  simba-download: https://github.com/Villavu/Simba/releases/download/simba1400-release/Simba-Win32.exe
  srl-download: https://github.com/Torwent/SRL-T.git

jobs:
  compile:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Simba
        shell: bash
        run: |
          cd ..
          curl --retry 5 -L -o ./Simba.exe ${{ env.simba-download }}
          mkdir ./Includes
          git clone ${{ env.srl-download }}
          mv ./SRL-T/ ./Includes/SRL-T/
          cp -r ./WaspLib/ ./Includes/WaspLib/
          echo '{$I SRL-T/osr.simba}{$I WaspLib/optional.simba}' > test.simba

      - name: Test Compile Includes
        shell: bash
        run: |
          cd ..
          ./Simba.exe --compile test.simba